---

# Timezone for the servers
timezone: "America/New_York"

# Set custom ntp servers
ntp_servers:
  primary:
  - "time.cloudflare.com"
  - "time.google.com"
  fallback:
  - "0.us.pool.ntp.org"
  - "1.us.pool.ntp.org"
  - "2.us.pool.ntp.org"
  - "3.us.pool.ntp.org"

# Additional ssh public keys to add to the nodes
ssh_authorized_keys:
# Linux Desktop
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzsu/AuBZkK5J9hZLya9ood8RuXqnN0Eo4hEeFvibuhQKyUerwLG1COa8d1QDXSJR37c/JjXKRzYX5JE347P48hU7dN+vnoi9uKuhHu7NILaLeo2QrQKTuWKygj23ee4EHj0B/XP562seqv9/zLmbaTZO3J1lXFugTVo0kXGbzCWQnOZyEEY+cUHhHVSu4/ugmkkUvV744CYo7TmcMwBjfrOnvamWVD09dYcX6wq0KLDU59BzVj6GNs8TbwUNR52EAYv0PXDPeKUkrMx5YaEGoc286kFWGiIJYSKMOukuZYPOSkgwONQSGt6Hvzft+eCxvR93J1vNcMIV1PjTfRdZvPa1mvJ1/uzWWWGQfODGKmBaDMZ4e2o4ItLJcopAUWbpr/bQIadCpt4ckKPJJ9km+qhYz+Np0ZfQ1Ay5NOTLZx3IhBuXHIxLIr0PialTig9+MXf1ZCwW2SI7kPrVVB5IwysA8R9Z/p7cnv0uOVNNfFMyIsI8jVnsqeRN4GFMweBY1kJwK4X7dnsKfoYWkjQ9DUaZ62wTk0u4P4zSGxEVx43rk/f2b+nXZbl1IhgA/2SV2b2eHIGHE6aSMSjUHXrZ7ZVJhAwqDFoN18NvBKOHQo6CKHG5jyvII4I8+NbnAGPG320VbvQoAA8nlUO8rsy05KdBU0U9UI3gq7bYWFJaKew== devin.kray@gmail.com"
# MacBook
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDO1R1i7dP0dY3f3rnlIQjVPsg3p0Xvz/16oZq+cUmE+O3An9qKQNUwWA98EdnMfq09qLpU1OBSafrLjZ8rd4+4KZJNhFgOCX1qq9GDo+o87toYZUvZ6ftdokpgYlYh0sSUxCjbEnaYAr9W2ZYs32fSJAZdoSydUp9gsTlYQJtq4OYKeQd4gd0oJ2F+L3Rv/HwY1U2+ynW4XnsnbfYky9DkQJIgirFwhwsuDot7VMW14mvI1T4IN+rGHfvHsEqsKrVCOUwfsgnNEXR4R5lSE0mNgZiEFnh/F7pA8QGmcKrNv/Fd4cZRdWxtDdrmEVVtbVnlnRrtV0NS9VqJiJm6Rm9QQ9LLemHAGJHT90hUknSB5qw1pxJ/uZ5hCQzOAzfABQ+Jgj4VzT4PpwaGF529v9VSsV6KPPyF0pP8YNKgRaSBxFqFTwIBLH9eBiE0neIHDGBBi3H9pbYtlMHoy9pnepSPPhD4vSiVbFVSFxwKJ9hoVpRKt3gZuhtIMuDVFpgiAHYE9VYSKbfH0FuBLqrNzF0inkn0Luo+wWyCUNO2y+mZZKpm61huCgdWGL4HfSNLKqwxBtG0oKI1GISGzipay9m0u0JrPjeNr0bD0Sg28aDhjEeds6P9Xe/j/QZg6YWW11rUH33GFljHo6Llu9rBfoiM9BJqXDyInkzfYcq91cojmw== devin.kray@gmail.com"
# iPhone
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXTx2RvLN5ZNNG8OM/0lgA4SRjihnwR57mvHCvaYcSXDsjTVq4NlzTG2kfccTIbNUR+g1t3RUJYeFgWFiY5yxHIupNbO2yDGpkSSVrvrrPGzIMQcMrGIJcF4RSVKaPJ60jDekYgPaV2Se49kfbR9Da6PHU66VnvF/JS3dhGS/wbiw3pVk/uIOaiKmg0Ix8uavhBbYMy9/SsfH5j/eR+rNpXH/HyLWpS39FS+Rvv0ndp0l4JnTTvZyLMptfB2Oqans0NuZn/VdRzyr/km7eOcAFskc4Ffv6F112KOHhYgvve3L9qXrZm0kaoYp9SsHuVbo8VtUlPNgpE4ZevtALgywJBBlCzkXvnrz7vU7iA9h0mePtoW7CWBYuJd533JxDX8Etb9FDl1+rryKYfqjVHO90+FN0xJDniiqYUApTokZkEbzp3Ob2fQyPGjc7uxXMUNhsJoi/GTJfIhdpwKs7fNBI6jpAkuGMo4OZH96LZJ1DtAxvG8pGPOxXt/67YO6gPWwU4A1hVHJ6137dzKpqgUSFIPz0OL18coj8jqmt2UJO48PdkfJ41M+/kqc/oHia+Y2pwXW4nRxBXG3YFnVDbIDZNwavv/AvP7ygp3wZnL61aiKG5mTIB949Lt3z8DCneUIcvFOqyYp/xutHoYL7p4yz/qltIQSjn8H4vOU6l4Mhew== devin.kray@gmail.com"

# Disable ipv6
disable_ipv6: false
